import { useState } from 'react';
import { apiFetch } from '../lib_api';
const API_URL = import.meta.env.VITE_API_URL || 'https://localfix-gv9q.onrender.com/api';
export default function Contact() {
  const [form,setForm]=useState({name:'',email:'',phone:'',message:''});
  const [state,setState]=useState({loading:false,error:'',success:''});
  const submit=async e=>{e.preventDefault();setState({loading:true,error:'',success:''});try{const r=await apiFetch(`/api/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.message);setState({loading:false,error:'',success:'Message sent successfully! We will contact you soon.'});setForm({name:'',email:'',phone:'',message:''});}catch(err){setState({loading:false,error:err.message||'Unable to send message',success:''});}};
  return <section id="contact" className="min-h-screen bg-gradient-to-br from-slate-100 via-blue-50 to-cyan-100 py-20"><div className="max-w-7xl mx-auto px-6"><div className="text-center mb-16"><span className="bg-blue-100 text-blue-700 px-5 py-2 rounded-full font-semibold">📞 Contact Us</span><h1 className="text-5xl font-extrabold text-slate-800 mt-6">Get In <span className="text-blue-600">Touch</span></h1><p className="text-gray-600 mt-4 text-lg max-w-2xl mx-auto">Need any home service? Send us a message and our team will contact you.</p></div><div className="grid lg:grid-cols-2 gap-10"><div className="bg-gradient-to-br from-blue-600 to-cyan-500 text-white rounded-3xl shadow-2xl p-10"><h2 className="text-3xl font-bold mb-10">Contact Information</h2><div className="space-y-6"><p>📍 Latur, Maharashtra, India</p><p>📞 +91 98765 43210</p><p>📧 localservices@gmail.com</p><p>🕒 Monday - Sunday, 9:00 AM - 8:00 PM</p></div></div><div className="bg-white rounded-3xl shadow-2xl p-10"><h2 className="text-3xl font-bold text-slate-800">Send Us a Message</h2>{state.error&&<p className="mt-4 p-3 rounded bg-red-50 text-red-600">{state.error}</p>}{state.success&&<p className="mt-4 p-3 rounded bg-green-50 text-green-600">{state.success}</p>}<form onSubmit={submit} className="space-y-5 mt-8"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Full Name" className="w-full p-4 rounded-xl border outline-none focus:ring-2 focus:ring-blue-300"/><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email Address" className="w-full p-4 rounded-xl border outline-none focus:ring-2 focus:ring-blue-300"/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Phone Number" className="w-full p-4 rounded-xl border outline-none focus:ring-2 focus:ring-blue-300"/><textarea required rows="5" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Write your message..." className="w-full p-4 rounded-xl border outline-none resize-none focus:ring-2 focus:ring-blue-300"/><button disabled={state.loading} className="w-full bg-blue-600 hover:bg-blue-700 text-white py-4 rounded-xl font-semibold disabled:opacity-60">{state.loading?'Sending...':'Send Message 🚀'}</button></form></div></div></div></section>;
}
