import { useEffect,useState } from 'react';
import { Link,useNavigate } from 'react-router-dom';
import { apiFetch, API_URL } from '../../lib_api';
export default function AdminDashboard(){
 const navigate=useNavigate(),token=localStorage.getItem('token'),user=JSON.parse(localStorage.getItem('user')||'null');
 const [stats,setStats]=useState(null),[bookings,setBookings]=useState([]),[services,setServices]=useState([]),[messages,setMessages]=useState([]),[editing,setEditing]=useState(null),[form,setForm]=useState({title:'',description:'',icon:'🛠️',rating:'5.0'}),[error,setError]=useState('');
 const auth={Authorization:`Bearer ${token}`};
 const load=async()=>{try{const [a,b,c,d]=await Promise.all([apiFetch(`/api/admin/stats`,{headers:auth}),apiFetch(`/api/bookings`,{headers:auth}),apiFetch(`/api/services`),apiFetch(`/api/messages`,{headers:auth})]);const aj=await a.json(),bj=await b.json(),cj=await c.json(),dj=await d.json();setStats(aj.stats);setBookings(bj.bookings||[]);setServices(cj.services||[]);setMessages(dj.messages||[]);}catch(e){setError(e.message)}};
 useEffect(()=>{if(!token)navigate('/login');else load();},[]);
 const logout=()=>{localStorage.clear();navigate('/login')};
 const saveService=async e=>{e.preventDefault();const url=editing?`/api/services/${editing}`:`/api/services`;const r=await apiFetch(url,{method:editing?'PUT':'POST',headers:{...auth,'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok){setError(d.message);return;}setEditing(null);setForm({title:'',description:'',icon:'🛠️',rating:'5.0'});load();};
 const removeService=async id=>{if(!confirm('Delete this service?'))return;await apiFetch(`/api/services/${id}`,{method:'DELETE',headers:auth});load()};
 const status=async(id,value)=>{await apiFetch(`/api/bookings/${id}/status`,{method:'PATCH',headers:{...auth,'Content-Type':'application/json'},body:JSON.stringify({status:value})});load()};
 return <div className="min-h-screen bg-slate-950 text-white"><header className="sticky top-0 z-10 bg-slate-900 border-b border-slate-800 px-6 py-4 flex justify-between items-center"><div><h1 className="text-xl font-bold">Admin Dashboard</h1><p className="text-xs text-slate-400">{user?.name}</p></div><div className="flex gap-3"><Link to="/" className="border border-slate-700 px-4 py-2 rounded-lg">View Home</Link><button onClick={logout} className="border border-slate-700 px-4 py-2 rounded-lg">Logout</button></div></header><main className="max-w-7xl mx-auto p-6 space-y-10">{error&&<div className="bg-red-500/10 text-red-400 p-3 rounded-lg">{error}</div>}
 <section><h2 className="text-2xl font-bold mb-5">Overview</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{(stats||[]).map(s=><div key={s.label} className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><p className="text-slate-400 text-sm">{s.label}</p><p className="text-3xl font-bold text-blue-400 mt-2">{s.value}</p></div>)}</div></section>
 <section><h2 className="text-2xl font-bold mb-5">Manage Services</h2><div className="grid lg:grid-cols-3 gap-5"><form onSubmit={saveService} className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-3"><h3 className="font-bold">{editing?'Modify Service':'Add Service'}</h3><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required placeholder="Service title" className="w-full bg-slate-800 p-3 rounded-lg"/><input value={form.icon} onChange={e=>setForm({...form,icon:e.target.value})} placeholder="Icon" className="w-full bg-slate-800 p-3 rounded-lg"/><input value={form.rating} onChange={e=>setForm({...form,rating:e.target.value})} placeholder="Rating" className="w-full bg-slate-800 p-3 rounded-lg"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required placeholder="Description" className="w-full bg-slate-800 p-3 rounded-lg"/><button className="w-full bg-blue-600 py-3 rounded-lg font-semibold">{editing?'Update Service':'Add Service'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm({title:'',description:'',icon:'🛠️',rating:'5.0'})}} className="w-full border border-slate-700 py-3 rounded-lg">Cancel</button>}</form><div className="lg:col-span-2 grid sm:grid-cols-2 gap-4">{services.map(s=><div key={s.id} className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="text-4xl">{s.icon}</div><h3 className="font-bold text-xl mt-3">{s.title}</h3><p className="text-slate-400 text-sm mt-2">{s.description}</p><p className="mt-2">⭐ {s.rating}</p><div className="flex gap-2 mt-4"><button onClick={()=>{setEditing(s.id);setForm({title:s.title,description:s.description,icon:s.icon,rating:s.rating})}} className="bg-yellow-500 text-black px-3 py-2 rounded-lg">Modify</button><button onClick={()=>removeService(s.id)} className="bg-red-600 px-3 py-2 rounded-lg">Remove</button></div></div>)}</div></div></section>
 <section><h2 className="text-2xl font-bold mb-5">Booking Management</h2><div className="overflow-auto bg-slate-900 border border-slate-800 rounded-2xl"><table className="w-full text-sm"><thead className="text-slate-400"><tr><th className="p-4 text-left">Customer</th><th className="p-4 text-left">Service</th><th className="p-4 text-left">Phone</th><th className="p-4 text-left">Status</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id} className="border-t border-slate-800"><td className="p-4">{b.fullName}<div className="text-xs text-slate-500">{b.email}</div></td><td className="p-4">{b.service}</td><td className="p-4">{b.phone}</td><td className="p-4"><select value={b.status} onChange={e=>status(b.id,e.target.value)} className="bg-slate-800 rounded-lg p-2"><option>Pending</option><option>In Progress</option><option>Completed</option><option>Cancelled</option></select></td></tr>)}</tbody></table></div></section>
 <section><h2 className="text-2xl font-bold mb-5"></h2><div className="grid md:grid-cols-2 gap-4">{messages.length?messages.map(m=><div key={m.id} className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="flex justify-between"><b>{m.name}</b><span className="text-xs text-slate-500">{new Date(m.createdAt).toLocaleString()}</span></div><p className="text-slate-400 text-sm mt-1">{m.email} {m.phone&&`• ${m.phone}`}</p><p className="mt-4">{m.message}</p></div>):<p className="text-slate-400"></p>}</div></section>
 </main></div>;
}
